# on:
#   push:
#     branches:
#       - main

# name: ðŸš€ Deploy website on push

# jobs:
#   web-deploy:
#     name: ðŸŽ‰ Deploy
#     runs-on: ubuntu-latest

#     steps:
#       - name: ðŸšš Get latest code
#         uses: actions/checkout@v4

#       - name: ðŸ“‚ Deploy via SFTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#         with:
#           server: 167.235.249.143
#           username: teclabs
#           password: YH49hHwQQjQjqJV5ZDwb
#           protocol: sftp
#           port: 22
#           server-dir: /home/teclabs/public_html/


